---
kind: pipeline
name: test

steps:
  - name: test
    image: alpine:3.12
    pull: always
    environment:
      CARGO_HOME: target/cargo
      RUST_BACKTRACE: 1
      RUST_LOG: debug
    commands:
      - apk add --no-cache cargo git
      - git log -n1
      - cargo -V
      - cargo test
  - name: notify
    image: plugins/matrix
    settings:
      homeserver: https://synapse.matrix.msrd0.de
      roomid: "#aatree:msrd0.de"
      username: drone
      password:
        from_secret: matrix_password

---
kind: pipeline
name: rustfmt

steps:
  - name: rustfmt
    image: iamsauravsharma/rust-fmt:nightly-alpine
    pull: always
    commands:
      - cargo fmt -- -V
      - cargo fmt -- --check -l
  - name: notify
    image: plugins/matrix
    settings:
      homeserver: https://synapse.matrix.msrd0.de
      roomid: "#aatree:msrd0.de"
      username: drone
      password:
        from_secret: matrix_password

---
kind: signature
hmac: 23d721af38594d533cdd40159932a262cb3154a790ceaae28f4ff5695138a607

...
