name: Documentation
on:
  push:
    branches: [master]

jobs:
  doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@beta
      - run: cargo doc --workspace --all-features
      - name: Push changes to gh-pages
        run: |
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git config user.name "${{ github.actor }}"
          git config -l

          git remote add origin-gh-pages https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git fetch origin-gh-pages
          git remote show origin-gh-pages
          git checkout gh-pages
          
          test ! -d ./doc || rm -r ./doc
          cp -R ./target/doc ./doc
          date >./doc/.timestamp
          
          git add ./doc
          git status
          git commit -m "Update Documentation for ${{ github.sha }}"
          git push origin-gh-pages gh-pages
