name: Rust

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test-lib:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@1.48.0
      - run: cargo test --workspace --all-features --lib
        env:
          RUST_BACKTRACE: 1
  
  test-doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test --workspace --all-features --doc
        env:
          RUST_BACKTRACE: 1
  
  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - run: cargo fmt --all -- --check
  
  doc:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo doc --workspace --all-features --no-deps
        env:
          RUSTDOCFLAGS: "--default-theme ayu"
      - name: Push changes to gh-pages
        run: |
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git config user.name "${{ github.actor }}"
          git config -l

          git remote add origin-gh-pages https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git fetch origin-gh-pages
          git remote show origin-gh-pages
          git checkout gh-pages
          
          test ! -d ./doc || rm -r ./doc
          cp -R ./target/doc ./doc
          date >./doc/.timestamp
          
          git add ./doc
          git status
          git commit -m "Update Documentation for ${{ github.sha }}"
          git push origin-gh-pages gh-pages
